version: "3.9"
services:
  mysql-customer:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'customer'
      MYSQL_USER: 'demo'
      MYSQL_PASSWORD: 'demo@123'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3307:3306'
    expose:
      - "3307"
    networks:
      - backend

  mysql-fraud:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'fraud'
      MYSQL_USER: 'demo'
      MYSQL_PASSWORD: 'demo@123'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3308:3306'
    expose:
      - "3308"
    networks:
      - backend

  mysql-notification:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'notification'
      MYSQL_USER: 'demo'
      MYSQL_PASSWORD: 'demo@123'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3309:3306'
    expose:
      - "3309"
    networks:
      - backend

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - '9411:9411'


networks:
  backend:
