application:
  title: Api-Gateway
  version: 0.0.1-SNAPSHOT

spring:
  application:
    name: api-gateway
  #Not mandatory to mention as this is the default url
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/v1/customers/**

server:
  port: 8085

#eurka server details
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true




